version: 1

honeycomb_team: prod # repo scoped OR could be near the env

deployment_gates:
  staging: # github env name
    queries:
      - honeycomb_environment: prod # honeycomb env to query against
        spec: &queryspec '{
            "time_range": 1800,
            "calculations": [
              {
                  "op": "COUNT"
              }
            ],
            "filters": [
              {
                  "column": "global.build_id",
                  "op": "=",
                  "value": "${GITHUB_RUN_ID}"
              }
            ]
          }'
        threshold:
          operator: '>'
          value: 10
  production:
    queries:
      - honeycomb_environment: prod
        spec: *queryspec
        threshold:
          operator: '>'
          value: 1