version: 1

honeycomb_team: my-team # repo scoped OR could be near the env

deployment_gates: 
  staging: # github env name
    queries:
      - honeycomb_environment: qa # honeycomb env to query against
        honeycomb_dataset: my-cool-application # optional, with no dataset indicating env-wide query
        spec: &queryspec '{
            "time_range": 1800,
            "calculations": [
              {
                  "op": "COUNT"
              }
            ],
            "filters": [
              {
                  "column": "status_code",
                  "op": "=",
                  "value": "500"
              },
              {
                  "column": "build_id",
                  "op": "=",
                  "value": ${ GH_RUN_ID }
              }
            ],
            "filter_combination": "AND"
          }'
        threshold:
          operator: <
          value: 1

    production:
      queries:
        - honeycomb_environment: staging
          honeycomb_dataset: my-cool-application
          spec: *queryspec
          threshold:
            operator: <
            value: 1