version: 1

honeycomb_team: api # repo scoped OR could be near the env

deployment_gates:
  staging: # github env name
    queries:
      - honeycomb_environment: development # honeycomb env to query against
        spec: &queryspec '{
            "time_range": 1800,
            "calculations": [
              {
                  "op": "COUNT"
              }
            ],
            "filters": [
              {
                  "column": "status_code",
                  "op": "=",
                  "value": "500"
              }
            ]
          }'
        threshold:
          operator: '>'
          value: 3
  production:
    queries:
      - honeycomb_environment: brooke
        spec: *queryspec
        threshold:
          operator: '>'
          value: 1