version: 1

honeycomb_team: demo

deployment_protection_rules:
  staging: # github env name
    queries:
      - honeycomb_environment: test # honeycomb env to query against
        spec: &queryspec '{
            "time_range": 1800,
            "calculations": [
              {
                  "op": "COUNT"
              }
            ],
            "filters": [
              {
                  "column": "http.status_code",
                  "op": "=",
                  "value": "500"
              },
              {
                  "column": "app.build_id",
                  "op": "=",
                  "value": "${GITHUB_RUN_ID}"
              }
            ],
            "filter_combination": "AND"
          }'
        threshold:
          operator: '>'
          value: 3
  production:
    queries:
      - honeycomb_environment: ms-demo
        spec: *queryspec
        threshold:
          operator: '>'
          value: 1
