version: 1

honeycomb_team: local

deployment_protection_rules:
  staging: # github env name
    queries:
      - honeycomb_environment: $classic$ # honeycomb env to query against
        honeycomb_dataset: dev
        spec: &queryspec '{
            "time_range": 1000,
            "calculations": [
              {
                  "op": "COUNT"
              }
            ],
            "filters": [
              {
                  "column": "status",
                  "op": "=",
                  "value": "500"
              },
              {
                  "column": "build_num",
                  "op": "=",
                  "value": "${GITHUB_RUN_ID}"
              }
            ],
            "filter_combination": "AND"
          }'
        threshold:
          operator: '>'
          value: 3
